### ISSUE TITLE
Deleting messages from Quickfilter does not work

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-web-interface#8]
You get the following exception in the Rails3 branch after clicking the "Delete all messages hit by this quickfilter" button:

```
undefined method `sources' for {:message=>/broken/, :deleted=>{"$in"=>[false, nil]}}:Hash
```

It's from this line in the MessagesController:

```
conditions = Message.all_by_quickfilter(filters_with_symbols, 0, 0).criteria.sources
```

(Introduced in fcf1cd98834f776605d27a9dcb51bea9ef309fce)
